### ISSUE TITLE
when Adding a new Prestation row ajax lookup does not work for the second add

### ISSUE THREAD

**Issue by mehditerraneen** [opefitoo/nursev3#14]
On First Prestation it works but on the next rows it does not. I noticed already this with this django ajax component. Please investigate if it can be solved easily  
![image](https://user-images.githubusercontent.com/1389899/33148300-9ad07d4c-cfcb-11e7-95c5-df208e0708f0.png)

**Comment by alexolkhovskii** [comment]
The issue is caused by https://djangopackages.org/packages/p/django-admin-bootstrapped/ package. It rewrites templates and changes one class. This change prevents a binding of jQuery event.
There are two options:
1) I can override template with origin class or add some custom js which to bind event to a new class;
2) Use another package to add nice styles to admin section;
I would recommend the second option as the most recent release of currently used package was 12/15/2015 As it is not maintained properly we may have issues with it in the future.
What is your opinion? Should I look for another package?

**Comment by mehditerraneen** [comment]
OK. Lets do solution 2. Which bootstrap package do you propose?
How about django 2 didnt they bootsrapped django admin already?

**Comment by alexolkhovskii** [comment]
Here is a list of options to customize admin dashboard:
https://github.com/no-dice/django-bootstrap-themes
https://github.com/fabiocaccamo/django-admin-interface
https://github.com/sainipray/djadmin
https://github.com/oscarmlage/django-cruds-adminlte
https://github.com/django-admin-tools/django-admin-tools
https://github.com/django-admin-bootstrap/django-admin-bootstrap
https://github.com/darklow/django-suit
https://github.com/viewflow/django-material

This one is the best in my opinion https://github.com/geex-arts/django-jet
There are several default design, so you can pick any of them and a lot of built-in functionality. At the first glance it is very flexible and easy to customize. There is also a fitler of choices, so we can probably avoid usage of ajaxadmin packages (if you like their default option).

**Comment by mehditerraneen** [comment]
Ok let's go for https://github.com/geex-arts/django-jet
